### ISSUE TITLE
2019《thought-sc2》以及2018年《On Reinforcement Learning for Full-length Game of StarCraft》相关提问

### ISSUE THREAD

**Issue by guobaoyo** [liuruoze/Thought-SC2-model-experiment#1]
刘老哥您好，我对星际争霸很感兴趣，最近在看强化学习在星际争霸上面的实验应用和论文，看到了俞老师组2018.2019年的工作，有个疑问想请问一下您，希望老哥您有时间回答一下。
1.看到这个是最近更新的，请问相比于https://github.com/StarBeta/Thought-SC2 之前的版本有什么更新点呢？
2.https://github.com/StarBeta/Thought-SC2 与本篇代码都是19年工作的代码，想问一下老哥18年《On Reinforcement Learning for Full-length Game of StarCraft》的代码有公开吗？可不可以问一下具体的训练细节？
3.您们在19年之后还有星际争霸的相关工作吗？

**Comment by liuruoze** [comment]
1. 这个代码相比https://github.com/StarBeta/Thought-SC2 的版本，有以下几点改进：1. 我们实现了一个WorldModel版本的SC2，相关信息可以查阅Arxiv上的同名论文“World Models, Ha et al”，是LSTM创始人的一个工作。我们比较了我们的方法与WorldModel的方法；2. 效果上的大幅提升，从对难度10的50%-60%的胜率提升到了90%，这样的提升来自好几个方面，包括算法，超参的优化，同时还由于我们引入的一个新架构XfrNet。

2. 18年的工作因为当时太早了，代码很多地方都不完美，所以没有公开。那个工作同时也正在改投期刊中，到时会有更多的细节。

3. 有一个工作正在进行中，但由于保密，暂时不便透露。到时会发布在这个github主页上，敬请期待。

**Comment by guobaoyo** [comment]
好的，感谢您的回复以及这篇开源代码，为我们提供了极大的帮助，谢谢您。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liuruoze/Thought-SC2-model-experiment"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月22日(星期四) 上午8:22
收件人:&nbsp;"liuruoze/Thought-SC2-model-experiment"<Thought-SC2-model-experiment@noreply.github.com&gt;;
抄送:&nbsp;"石成功"<1415500736@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [liuruoze/Thought-SC2-model-experiment] 2019《thought-sc2》以及2018年《On Reinforcement Learning for Full-length Game of StarCraft》相关提问 (#1)





  
 
这个代码相比https://github.com/StarBeta/Thought-SC2 的版本，有以下几点改进：1. 我们实现了一个WorldModel版本的SC2，相关信息可以查阅Arxiv上的同名论文“World Models, Ha et al”，是LSTM创始人的一个工作。我们比较了我们的方法与WorldModel的方法；2. 效果上的大幅提升，从对难度10的50%-60%的胜率提升到了90%，这样的提升来自好几个方面，包括算法，超参的优化，同时还由于我们引入的一个新架构XfrNet。
 
 
 
18年的工作因为当时太早了，代码很多地方都不完美，所以没有公开。那个工作同时也正在改投期刊中，到时会有更多的细节。
 
 
 
有一个工作正在进行中，但由于保密，暂时不便透露，敬请关注这个github主页。

**Comment by liuruoze** [comment]
不客气，您言重了。
